kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven:3.6.3-openjdk-11
  commands:
  - mvn clean install -DskipTests
- name: docker  
  image: plugins/docker
  settings:
    username: dindocker13
    password: docker@123
    repo: dindocker13/drone-demo
