kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven:3.6.3-openjdk-11
  commands:
  - mvn clean install package -Dmaven.test.skip=true -Dpmd.failOnViolation=false
  
- name: docker  
  image: plugins/docker
  settings:
    username: parthsharma97
    password: P@rth123$
    repo: parthsharma97/droneci
